/**
 * Global TypeScript types for the IoT/AIoT application.
 * All shared interfaces, enums, and type aliases are defined here.
 */

// =============================================================================
// Sensor Types
// =============================================================================

/** Supported sensor types in the IoT simulation */
export type SensorType =
  | 'temperature'
  | 'humidity'
  | 'motion'
  | 'energy'
  | 'air_quality';

/** Units of measurement for each sensor type */
export type SensorUnit = '°C' | '%' | 'bool' | 'kWh' | 'AQI';

/** Mapping from sensor type to its unit */
export const SENSOR_UNITS: Record<SensorType, SensorUnit> = {
  temperature: '°C',
  humidity: '%',
  motion: 'bool',
  energy: 'kWh',
  air_quality: 'AQI',
};

// =============================================================================
// Database Models
// =============================================================================

/** A single sensor reading stored in SQLite */
export interface SensorReading {
  id: number;
  sensorType: SensorType;
  value: number;
  unit: SensorUnit;
  timestamp: string; // ISO 8601 format
  isAnomaly: boolean;
}

/** Row shape returned from SQLite for sensor_readings table */
export interface SensorReadingRow {
  id: number;
  sensor_type: string;
  value: number;
  unit: string;
  timestamp: string;
  is_anomaly: number; // SQLite boolean: 0 or 1
}

/** An alert generated by the AI engine or rule system */
export interface Alert {
  id: number;
  sensorType: SensorType;
  message: string;
  severity: SeverityLevel;
  timestamp: string; // ISO 8601 format
  acknowledged: boolean;
}

/** Row shape returned from SQLite for alerts table */
export interface AlertRow {
  id: number;
  sensor_type: string;
  message: string;
  severity: string;
  timestamp: string;
  acknowledged: number; // SQLite boolean: 0 or 1
}

/** A key-value setting stored in SQLite */
export interface Setting {
  id: number;
  key: string;
  value: string;
}

// =============================================================================
// Severity & Status
// =============================================================================

/** Alert severity levels */
export type SeverityLevel = 'info' | 'warning' | 'critical';

/** System health status */
export type SystemStatus = 'normal' | 'warning' | 'critical';

/** Sensor value status relative to thresholds */
export type ValueStatus = 'normal' | 'approaching' | 'exceeded';

// =============================================================================
// Sensor Data State
// =============================================================================

/** Current state of a single sensor */
export interface SensorState {
  type: SensorType;
  currentValue: number;
  unit: SensorUnit;
  status: ValueStatus;
  trend: TrendDirection;
  lastUpdated: string;
  history: SensorReading[];
}

/** Direction of the value trend based on regression */
export type TrendDirection = 'rising' | 'falling' | 'stable';

// =============================================================================
// Threshold Configuration
// =============================================================================

/** Threshold configuration for a single sensor type */
export interface ThresholdConfig {
  sensorType: SensorType;
  minWarning: number;
  maxWarning: number;
  minCritical: number;
  maxCritical: number;
  label: string;
  unit: SensorUnit;
}

// =============================================================================
// AI Engine Types
// =============================================================================

/** Result of Z-Score anomaly detection */
export interface AnomalyResult {
  isAnomaly: boolean;
  zScore: number;
  mean: number;
  standardDeviation: number;
  value: number;
}

/** Result of linear regression prediction */
export interface PredictionResult {
  predictedValue: number;
  trend: TrendDirection;
  slope: number;
  confidence: number; // R² value (0-1)
  minutesAhead: number;
}

/** Rule evaluation result from the AI engine */
export interface RuleEvaluationResult {
  triggered: boolean;
  message: string;
  severity: SeverityLevel;
  action: string;
}

// =============================================================================
// Weather API Types
// =============================================================================

/** Parsed weather data from OpenWeatherMap */
export interface WeatherData {
  temperature: number;
  humidity: number;
  pressure: number;
  description: string;
  icon: string;
  city: string;
  country: string;
  windSpeed: number;
  feelsLike: number;
  timestamp: string;
}

/** OpenWeatherMap API response structure */
export interface OpenWeatherMapResponse {
  main: {
    temp: number;
    feels_like: number;
    humidity: number;
    pressure: number;
  };
  weather: Array<{
    description: string;
    icon: string;
  }>;
  wind: {
    speed: number;
  };
  name: string;
  sys: {
    country: string;
  };
}

// =============================================================================
// App Store Types (Zustand)
// =============================================================================

/** Simulation speed options */
export type SimulationSpeed = 'fast' | 'normal' | 'slow';

/** Simulation speed intervals in milliseconds */
export const SIMULATION_INTERVALS: Record<SimulationSpeed, number> = {
  fast: 2000,
  normal: 3000,
  slow: 5000,
};

/** Application settings stored in the Zustand store */
export interface AppSettings {
  isDarkMode: boolean;
  alertsEnabled: boolean;
  simulationSpeed: SimulationSpeed;
  useRealWeather: boolean;
  weatherApiKey: string;
  weatherCity: string;
}

/** Chart data point for time-series rendering */
export interface ChartDataPoint {
  timestamp: string;
  value: number;
  label: string;
  isAnomaly: boolean;
}

/** Statistics summary for a set of readings */
export interface StatsSummary {
  min: number;
  max: number;
  average: number;
  standardDeviation: number;
  count: number;
}

/** Time period options for history filtering */
export type TimePeriod = '1h' | '6h' | '24h' | '7d' | '30d';

/** Mapping from time period to milliseconds */
export const TIME_PERIOD_MS: Record<TimePeriod, number> = {
  '1h': 60 * 60 * 1000,
  '6h': 6 * 60 * 60 * 1000,
  '24h': 24 * 60 * 60 * 1000,
  '7d': 7 * 24 * 60 * 60 * 1000,
  '30d': 30 * 24 * 60 * 60 * 1000,
};
